name: "Main Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: setup-java-17
        name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - uses: burrunan/gradle-cache-action@v1.10
        with:
          remote-build-cache-proxy-enabled: false
          arguments: build --stacktrace
          properties: |
            org.gradle.java.installations.paths=${{ steps.setup-java-17.outputs.path }}
      - uses: burrunan/gradle-cache-action@v1.10
        with:
          remote-build-cache-proxy-enabled: false
          arguments: snapshot --stacktrace
          properties: |
            org.gradle.java.installations.paths=${{ steps.setup-java-17.outputs.path }}
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
